painelprecostcego/consultaproduto/urls.py
from django.urls import path
from consultaproduto import views

app_name = 'consultaproduto'

urlpatterns = [
    path('', views.index, name='index'),
    path('consulta/', views.consulta, name='consulta'),
]

painelprecostcego/painelprecostcego/urls.py
from django.contrib import admin
from django.urls import path, include
from consultaproduto.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('consultaproduto/', include('consultaproduto.urls')),
    path('', index, name='index'),
]

painelprecostcego/consultaproduto/models.py
from django.db import models

# Create your models here.

painelprecostcego/consultaproduto/forms.py
from django import forms


class BuscaProdutoForm(forms.Form):
    descricao = forms.CharField(label='Descrição', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    numero_resultados = forms.IntegerField(
        label='Número de resultados',
        min_value=100,
        max_value=1000,
        widget=forms.NumberInput(attrs={'class': 'form-control mb-3', 'value': 100}),
        )

painelprecostcego/consultaproduto/views.py
from multiprocessing import context
from django.shortcuts import render

from consultaproduto.forms import BuscaProdutoForm
from consultaproduto.search import search_produto

# Create your views here.


def index(request):
    return render(request, 'consultaproduto/index.html')


def consulta(request):
    form = BuscaProdutoForm()
    context = {
        'form': form,
    }
    if request.method == 'POST':
        form = BuscaProdutoForm(request.POST)
        if form.is_valid():
            descricao = form.cleaned_data['descricao']
            numero_resultados = form.cleaned_data['numero_resultados']
            print(numero_resultados)
            results = search_produto(descricao, numero_resultados)

            # group results by ean
            results_grouped = {}
            for result in results:
                if result['ean'] in results_grouped:
                    if result['description'] not in results_grouped[result['ean']][0]:
                        results_grouped[result['ean']][0].append(result['description'].title())
                    results_grouped[result['ean']][1].append(float(result['price']))
                else:
                    results_grouped[result['ean']] = [
                        [result['description'].title()],
                        [float(result['price'])]
                    ]
            # calculate average price and concatenate descriptions
            produtos = []
            for ean in results_grouped.keys():
                price = sum(results_grouped[ean][1]) / len(results_grouped[ean][1])
                std = sum((x - price) ** 2 for x in results_grouped[ean][1]) / len(results_grouped[ean][1])
                produtos.append({
                    'ean': f'{ean} (x{len(results_grouped[ean][1])})',
                    'descricao':  ' || '.join(results_grouped[ean][0]),
                    'preco': f'R${price:.2f}+/-{std:.2f}',
                }
                )


            # produtos = []
            # for hit in results:
            #     price = hit['price']
            #     produtos.append({
            #         'ean': hit['ean'],
            #         'descricao': hit['description'].title(),
            #         'preco': f'R$ {price:.2f}',
            #     }
            #     )
            context['produtos'] = produtos
    return render(request, 'consultaproduto/consulta.html', context)

painelprecostcego/templates/consultaproduto/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    {% block head %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-black mb-3 sticky-top">
        <a class="navbar-brand p-2" href="{% url 'index' %}">TCE-GO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'consultaproduto:consulta' %}">Consulta de produtos</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>

</html>

painelprecostcego/templates/consultaproduto/consulta.html
<!DOCTYPE html>

{% extends "consultaproduto/base.html"%}

{% block head %}
<title>Consulta de Produtos</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row mb-3">
        <div class="col-md-12">
            <h1>Consulta de Produtos</h1>
        </div>
    </div>
    <div class="row mb-3">
        <div class="card">
            <div class="card-body">
                <form method="post" class="form form-inline">
                    <div class="row">
                        {{ form }}
                        {% csrf_token %}
                    </div>
                    <div class="row mb-3">
                        <input type="submit" value="Buscar" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% if produtos %}
<div class="container">
    <table class="table table-bordered table-hover table-responsive">
        <thead>
            <th>EAN</th>
            <th>Descrição</th>
            <th>Preço</th>
        </thead>
        <tbody>
            {% for produto in produtos %}
            <tr>
                <td>{{ produto.ean }}</td>
                <td>{{ produto.descricao }}</td>
                <td>{{ produto.preco }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}

painelprecostcego/templates/consultaproduto/index.html
<!DOCTYPE html>

{% extends "consultaproduto/base.html"%}

{% block head %}
<title>Consulta de Produtos</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row mb-3">
        <h1>Homepage da Consulta de Produtos</h1>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <p>Ferramenta de consulta de produtos desenvolvida pelo TCE-GO</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}